---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_cloud_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    # filebeat传送到elasticsearch指定索引名称模板
    setup.template.name: "${ELASTICSEARCH_INDEX}"
    setup.template.pattern: "${ELASTICSEARCH_INDEX}-*"
    output.elasticsearch:
      # elasticsearch的IP地址和端口
      hosts: ["${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
      # elasticsearch的用户名称和密码
      #username: ${ELASTICSEARCH_USERNAME}
      #password: ${ELASTICSEARCH_PASSWORD}
      # filebeat传送到elasticsearch指定索引名称
      index: '${ELASTICSEARCH_INDEX}-%{+YYYY.MM.dd}'
      # 注意：只设置index没有设置setup.template.name和setup.template.pattern启动的时候会报以下错误:
      # setup.template.name and setup.template.pattern have to be set if index name is modified."

# 下面配置的变量，需要在部署的时候在env指定相关配置
# ELASTICSEARCH_INDEX
# ELASTICSEARCH_HOST
# ELASTICSEARCH_PORT
# ELASTICSEARCH_USERNAME
# ELASTICSEARCH_PASSWORD
