apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-lb
spec:
  rules:
  - host: web.devopssec.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 80
