kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - name: db
    port: 9200
    targetPort: 9200
    nodePort: 32000
  - name: transport
    port: 9300
    targetPort: 9300
